set_property PACKAGE_PIN E3 [get_ports CLK]
set_property PACKAGE_PIN P18 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports {inr[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_value[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_value[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_value[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_value[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_value[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_value[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_value[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_value[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_value[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_value[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_value[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_value[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_value[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_value[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_value[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_value[0]}]
set_property PACKAGE_PIN M13 [get_ports {inr[2]}]
set_property PACKAGE_PIN L16 [get_ports {inr[1]}]
set_property PACKAGE_PIN J15 [get_ports {inr[0]}]
set_property PACKAGE_PIN V12 [get_ports {out_value[14]}]
set_property PACKAGE_PIN V11 [get_ports {out_value[15]}]
set_property PACKAGE_PIN V14 [get_ports {out_value[13]}]
set_property PACKAGE_PIN V15 [get_ports {out_value[12]}]
set_property PACKAGE_PIN T16 [get_ports {out_value[11]}]
set_property PACKAGE_PIN U14 [get_ports {out_value[10]}]
set_property PACKAGE_PIN T15 [get_ports {out_value[9]}]
set_property PACKAGE_PIN V16 [get_ports {out_value[8]}]
set_property PACKAGE_PIN U16 [get_ports {out_value[7]}]
set_property PACKAGE_PIN U17 [get_ports {out_value[6]}]
set_property PACKAGE_PIN V17 [get_ports {out_value[5]}]
set_property PACKAGE_PIN R18 [get_ports {out_value[4]}]
set_property PACKAGE_PIN N14 [get_ports {out_value[3]}]
set_property PACKAGE_PIN J13 [get_ports {out_value[2]}]
set_property PACKAGE_PIN K15 [get_ports {out_value[1]}]
set_property PACKAGE_PIN H17 [get_ports {out_value[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports button_in]
set_property PACKAGE_PIN N17 [get_ports button_in]




